param(
    [Parameter(Mandatory=$true)][ValidateSet('select','prepare','finalize','promote','discard')][string]$Operation,
    [string]$ProjectDir,
    [string]$ConfigDir,
    [string]$RoutingConfigPath,
    [string]$TaskId,
    [string]$AttemptId,
    [string]$FrozenTarget,
    [ValidateSet('PATCH','BOUNDED_FEATURE','MAJOR_FEATURE','EXISTING_PRODUCT_EVOLUTION','NEW_PRODUCT','HIGH_RISK_CHANGE')][string]$WorkClass,
    [string]$FailureClass,
    [string]$FailedRoute,
    [string[]]$AttemptedRoute=@(),
    [string]$RouteAgent,
    [string]$PacketSha256,
    [string]$ReportPath
)
$ErrorActionPreference='Stop'
$WorkClasses=@('PATCH','BOUNDED_FEATURE','MAJOR_FEATURE','EXISTING_PRODUCT_EVOLUTION','NEW_PRODUCT','HIGH_RISK_CHANGE')
$Eligible=@('PROVIDER_UNAVAILABLE','RATE_LIMIT','PLAN_QUOTA_EXHAUSTED','MODEL_RETIRED','MODEL_TEMPORARILY_UNAVAILABLE','BOUNDED_TIMEOUT')
$Derived='MODEL_UNAVAILABLE_ON_ALL_CONFIGURED_PROVIDERS'
if(-not $ConfigDir){$ConfigDir=if($env:OPENCODE_CONFIG_DIR){$env:OPENCODE_CONFIG_DIR}else{Join-Path $HOME '.config\opencode'}}
if(-not $RoutingConfigPath){$RoutingConfigPath=Join-Path $ConfigDir 'opencode-governance-routing.json'}
function Load-Routing(){if(-not(Test-Path $RoutingConfigPath -PathType Leaf)){throw "Routing manifest not found: $RoutingConfigPath"};try{$r=Get-Content $RoutingConfigPath -Raw|ConvertFrom-Json}catch{throw 'Routing manifest is invalid JSON.'};if([string]$r.schema_version-ne'1.0'){throw 'Routing schema_version must be 1.0.'};if('executor'-notin@($r.settings.enabled_roles)){throw 'Executor failover is not enabled.'};return $r}
function Get-OnlyOn([object]$c){if(-not$c.PSObject.Properties['only_on']){throw 'Every Executor route must define only_on.'};return @($c.only_on|Where-Object{-not[string]::IsNullOrWhiteSpace([string]$_)})}
function Get-WorkClasses([object]$c){$v=@($c.work_classes|Where-Object{-not[string]::IsNullOrWhiteSpace([string]$_)});if($v.Count-eq0){return $WorkClasses};foreach($x in $v){if([string]$x-notin$WorkClasses){throw 'Executor route contains an invalid work class.'}};return $v}
function Get-Routes([object]$r){$cfg=$r.roles.executor;$out=@([pscustomobject]@{route_agent='executor';priority=0;candidate=$cfg.primary});foreach($c in @($cfg.fallbacks|Sort-Object{[int]$_.priority})){$out+=[pscustomobject]@{route_agent="executor-fallback-$([int]$c.priority)";priority=[int]$c.priority;candidate=$c}};return $out}
function Get-StatePath(){return Join-Path $ConfigDir 'opencode-governance-routing-state.tsv'}
function Get-Epoch(){return[DateTimeOffset]::UtcNow.ToUnixTimeSeconds()}
function Load-Cooldowns(){$m=@{};$p=Get-StatePath;if(Test-Path$p){foreach($line in Get-Content$p){$parts=$line-split"`t",2;if($parts.Count-eq2){$until=0;if([long]::TryParse($parts[1],[ref]$until)-and$until-gt(Get-Epoch)){$m[$parts[0]]=$until}}}};return$m}
function Save-Cooldowns([hashtable]$m){New-Item-ItemType Directory-Force-Path $ConfigDir|Out-Null;$lines=@();foreach($k in($m.Keys|Sort-Object)){$lines+="$k`t$($m[$k])"};[IO.File]::WriteAllLines((Get-StatePath),$lines,(New-Object Text.UTF8Encoding($false)))}
function Find-Route([object]$r,[string]$agent){foreach($x in(Get-Routes$r)){if($x.route_agent-eq$agent){return$x}};throw"Unknown Executor route agent: $agent"}
function Invoke-Git([string]$dir,[string[]]$args,[bool]$AllowFailure=$false){$out=&git-C $dir @args 2>&1;$code=$LASTEXITCODE;if(-not$AllowFailure-and$code-ne0){throw(($out-join"`n").Trim())};return[pscustomobject]@{code=$code;text=($out-join"`n")}}
function Validate-Id([string]$v,[string]$label){if([string]::IsNullOrWhiteSpace($v)-or$v-notmatch'^[A-Za-z0-9._-]+$'){throw"Invalid $label."}}
function Get-Project(){if(-not$ProjectDir){throw'--ProjectDir is required.'};$p=(Resolve-Path$ProjectDir).Path;Invoke-Git$p@('rev-parse','--is-inside-work-tree')|Out-Null;Validate-Id$TaskId'task id';Validate-Id$AttemptId'attempt id';return$p}
function Get-Status([string]$p){$raw=&git-C $p status --porcelain=v1 --untracked-files=all;$items=@($raw|Where-Object{$_-notmatch'^..\s+"?\.ai([\\/]|"?$)'}|Sort-Object);return$items}
function Get-StatusPaths([string[]]$entries){$set=[Collections.Generic.HashSet[string]]::new();foreach($e in$entries){$body=if($e.Length-ge4){$e.Substring(3)}else{$e};if($body.Contains(' -> ')){$body=$body.Split(@(' -> '),2,[StringSplitOptions]::None)[1]};$null=$set.Add($body.Trim('"').Replace('\','/'))};return$set}
function Get-ShaText([string]$t){$sha=[Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($t)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Get-Paths([string]$p,[string]$task,[string]$attempt){$root=Join-Path$p".ai\tasks\$task\evidence\executor-attempts";New-Item-ItemType Directory-Force-Path$root|Out-Null;return[pscustomobject]@{manifest=Join-Path$root"$attempt.json";patch=Join-Path$root"$attempt.patch"}}
function Read-Attempt([string]$p){$paths=Get-Paths$p$TaskId$AttemptId;if(-not(Test-Path$paths.manifest)){throw"Executor attempt manifest not found: $($paths.manifest)"};return[pscustomobject]@{data=(Get-Content$paths.manifest-Raw|ConvertFrom-Json);paths=$paths}}
function Write-Json([object]$o,[string]$p){[IO.File]::WriteAllText($p,(($o|ConvertTo-Json-Depth30)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)))}
function Resolve-Report([string]$p){if([IO.Path]::IsPathRooted($ReportPath)){return$ReportPath};return Join-Path$p$ReportPath}
function Select-Route([object]$r){if(-not$WorkClass){throw'--WorkClass is required for select.'};$attempted=[Collections.Generic.HashSet[string]]::new();foreach($x in$AttemptedRoute){$null=$attempted.Add($x)};$cool=Load-Cooldowns;$now=Get-Epoch;$failed=if($FailedRoute){Find-Route$r$FailedRoute}else{$null};$candidates=@();foreach($route in(Get-Routes$r)){$c=$route.candidate;if($attempted.Contains($route.route_agent)){continue};if($cool.ContainsKey([string]$c.model)-and$cool[[string]$c.model]-gt$now){continue};if($WorkClass-notin@(Get-WorkClasses$c)){continue};$scope=@(Get-OnlyOn$c);if($FailureClass){if($FailureClass-notin$Eligible-and$FailureClass-ne$Derived){continue};if($scope.Count-gt0-and$FailureClass-notin$scope){$sameLeft=@((Get-Routes$r)|Where-Object{$failed-and$_.candidate.model_family-eq$failed.candidate.model_family-and-not$attempted.Contains($_.route_agent)-and$WorkClass-in@(Get-WorkClasses$_.candidate)});if(-not($Derived-in$scope-and$sameLeft.Count-eq0)){continue}};if($FailureClass-in@('MODEL_RETIRED',$Derived)-and$failed-and$c.model_family-eq$failed.candidate.model_family){continue}};$candidates+=$route};if($candidates.Count-eq0){throw'EXECUTOR_FAILOVER_BLOCKED: no eligible route remains. HUMAN_RECOVERY_REQUIRED'};$family=if($failed){[string]$failed.candidate.model_family}else{''};$chosen=@($candidates|Sort-Object@{Expression={if($FailureClass-and$family-and$_.candidate.model_family-eq$family){0}else{1}}},priority)[0];$c=$chosen.candidate;[pscustomobject]@{route_agent=$chosen.route_agent;model=$c.model;variant=$c.variant;model_family=$c.model_family;priority=$chosen.priority;work_class=$WorkClass}|ConvertTo-Json-Compress}
function Prepare([object]$r){$p=Get-Project;if(-not$FrozenTarget-or$FrozenTarget-notmatch'^[0-9a-fA-F]{7,64}$'){throw'A Git frozen target SHA is required.'};if(-not$RouteAgent-or$PacketSha256-notmatch'^[0-9a-fA-F]{64}$'){throw'Route agent and 64-character packet SHA-256 are required.'};if(-not$WorkClass){throw'--WorkClass is required.'};$route=Find-Route$r$RouteAgent;Invoke-Git$p@('cat-file','-e',"$FrozenTarget^{commit}")|Out-Null;$resolved=(Invoke-Git$p@('rev-parse',$FrozenTarget)).text.Trim();$head=(Invoke-Git$p@('rev-parse','HEAD')).text.Trim();if($head-ne$resolved){throw'EXECUTOR_FAILOVER_BLOCKED: real HEAD differs from frozen target.'};$worktree=Join-Path$p".ai\executor-worktrees\$AttemptId";if(Test-Path$worktree){throw'Executor attempt worktree already exists.'};$pre=@(Get-Status$p);Invoke-Git$p@('worktree','add','--detach',$worktree,$FrozenTarget)|Out-Null;$paths=Get-Paths$p$TaskId$AttemptId;$data=[ordered]@{schema_version='1.0';state='PREPARED';task_id=$TaskId;attempt_id=$AttemptId;work_class=$WorkClass;route_agent=$RouteAgent;model=$route.candidate.model;variant=$route.candidate.variant;model_family=$route.candidate.model_family;frozen_target=$resolved;packet_sha256=$PacketSha256.ToLowerInvariant();execution_root=$worktree;pre_status=$pre;pre_status_sha256=Get-ShaText($pre-join"`0");created_at=[DateTime]::UtcNow.ToString('o')};Write-Json$data$paths.manifest;[pscustomobject]@{execution_root=$worktree;attempt_manifest=$paths.manifest;route_agent=$RouteAgent}|ConvertTo-Json-Compress}
function Finalize([object]$r){$p=Get-Project;$a=Read-Attempt$p;$d=$a.data;if($d.state-ne'PREPARED'){throw'Executor attempt is not PREPARED.'};if(-not$ReportPath){throw'--ReportPath is required.'};$reportFile=Resolve-Report$p;try{$report=Get-Content$reportFile-Raw|ConvertFrom-Json}catch{throw'Executor report must be valid JSON.'};$checks=@{EXECUTOR_ATTEMPT_ID=$d.attempt_id;PACKET_SHA256=$d.packet_sha256;FROZEN_TARGET_SHA=$d.frozen_target;REPORT_COMPLETE='YES'};foreach($k in$checks.Keys){if(([string]$report.$k).ToLowerInvariant()-ne([string]$checks[$k]).ToLowerInvariant()){throw"Executor report mismatch: $k"}};$worktree=[string]$d.execution_root;$status=&git-C$worktree status --porcelain=v1 --untracked-files=all;foreach($path in(Get-StatusPaths@($status))){if($path-eq'.ai'-or$path.StartsWith('.ai/')-or$path-eq'.git'-or$path.StartsWith('.git/')){throw"Executor attempt changed forbidden path: $path"}};Invoke-Git$worktree@('add','-A')|Out-Null;$patchBytes=&git-C$worktree diff --cached --binary --full-index|Out-String;[IO.File]::WriteAllText($a.paths.patch,$patchBytes,(New-Object Text.UTF8Encoding($false)));$changed=@((&git-C$worktree diff --cached --name-only)|ForEach-Object{$_.Replace('\','/')});$d.state='FINALIZED';$d|Add-Member NoteProperty report_path $reportFile -Force;$d|Add-Member NoteProperty report_sha256 (Get-FileHash$reportFile-Algorithm SHA256).Hash.ToLowerInvariant()-Force;$d|Add-Member NoteProperty patch_path $a.paths.patch -Force;$d|Add-Member NoteProperty patch_sha256 (Get-FileHash$a.paths.patch-Algorithm SHA256).Hash.ToLowerInvariant()-Force;$d|Add-Member NoteProperty changed_paths $changed -Force;$d|Add-Member NoteProperty finalized_at ([DateTime]::UtcNow.ToString('o'))-Force;Write-Json$d$a.paths.manifest;[pscustomobject]@{patch_path=$a.paths.patch;patch_sha256=$d.patch_sha256;changed_paths=$changed}|ConvertTo-Json-Compress}
function Promote([object]$r){$p=Get-Project;$a=Read-Attempt$p;$d=$a.data;if($d.state-ne'FINALIZED'){throw'Executor attempt is not FINALIZED.'};if((Invoke-Git$p@('rev-parse','HEAD')).text.Trim()-ne$d.frozen_target){throw'EXECUTOR_FAILOVER_BLOCKED: real HEAD changed before promotion.'};$current=@(Get-Status$p);if(($current|ConvertTo-Json-Compress)-ne(@($d.pre_status)|ConvertTo-Json-Compress)){throw'EXECUTOR_FAILOVER_BLOCKED: real worktree state changed before promotion.'};$dirty=Get-StatusPaths@($d.pre_status);$overlap=@($d.changed_paths|Where-Object{$dirty.Contains([string]$_)});if($overlap.Count){throw"EXECUTOR_FAILOVER_BLOCKED: proposed patch overlaps pre-existing dirty paths: $($overlap-join',')"};if((Get-FileHash$a.paths.patch-Algorithm SHA256).Hash.ToLowerInvariant()-ne$d.patch_sha256){throw'Executor patch hash mismatch.'};$check=Invoke-Git$p@('apply','--check','--binary',$a.paths.patch)$true;if($check.code-ne0){throw"EXECUTOR_FAILOVER_BLOCKED: patch apply check failed: $($check.text)"};Invoke-Git$p@('apply','--binary',$a.paths.patch)|Out-Null;$reverse=Invoke-Git$p@('apply','--check','--reverse','--binary',$a.paths.patch)$true;if($reverse.code-ne0){throw'EXECUTOR_FAILOVER_BLOCKED: applied patch verification failed.'};Invoke-Git$p@('worktree','remove','--force',[string]$d.execution_root)|Out-Null;$d.state='PROMOTED';$d|Add-Member NoteProperty promoted_at ([DateTime]::UtcNow.ToString('o'))-Force;$d|Add-Member NoteProperty post_status @(Get-Status$p)-Force;Write-Json$d$a.paths.manifest;[pscustomobject]@{state='PROMOTED';changed_paths=$d.changed_paths;patch_sha256=$d.patch_sha256}|ConvertTo-Json-Compress}
function Discard([object]$r){$p=Get-Project;$a=Read-Attempt$p;$d=$a.data;if(Test-Path([string]$d.execution_root)){Invoke-Git$p@('worktree','remove','--force',[string]$d.execution_root)|Out-Null};if($FailureClass){if($FailureClass-notin$Eligible){throw'Cannot mark cooldown for an ineligible failure.'};$m=Load-Cooldowns;$m[[string]$d.model]=(Get-Epoch)+[int]$r.settings.default_cooldown_seconds;Save-Cooldowns$m};$d.state='DISCARDED';$d|Add-Member NoteProperty discarded_at ([DateTime]::UtcNow.ToString('o'))-Force;$d|Add-Member NoteProperty failure_class $FailureClass -Force;Write-Json$d$a.paths.manifest;[pscustomobject]@{state='DISCARDED';route_agent=$d.route_agent}|ConvertTo-Json-Compress}
$r=Load-Routing
switch($Operation){'select'{Select-Route$r};'prepare'{Prepare$r};'finalize'{Finalize$r};'promote'{Promote$r};'discard'{Discard$r}}
