param(
    [string]$ConfigDir,
    [string]$ArchitectModel,
    [string]$ArchitectVariant,
    [string]$ExecutorModel,
    [string]$ExecutorVariant,
    [string]$ReviewerImplementationModel,
    [string]$ReviewerImplementationVariant,
    [string]$ReviewerArchitectureModel,
    [string]$ReviewerArchitectureVariant,
    [string]$FinalReviewerModel,
    [string]$FinalReviewerVariant,
    [string]$RoutingConfigPath,
    [switch]$NonInteractive
)
$ErrorActionPreference='Stop'
if(-not$ConfigDir){$ConfigDir=if($env:OPENCODE_CONFIG_DIR){$env:OPENCODE_CONFIG_DIR}else{Join-Path$HOME'.config\opencode'}}
$RootDir=Split-Path-Parent$PSScriptRoot;$Stamp=Get-Date-Format'yyyyMMdd-HHmmss';$BackupDir=Join-Path$ConfigDir"backups\opencode-governance-$Stamp";$RoutingManifestPath=Join-Path$ConfigDir'opencode-governance-routing.json'
$PublicAgents=@('architect','build','plan','executor','reviewer','reviewer-architecture','final-reviewer');$Commands=@('ai-init','ai-audit','ai-docs','ai-discover','ai-plan','ai-execute','ai-review','ai-workflow','ai-status','ai-resume','ai-metrics','ai-release')
$SupportedFailoverRoles=@('architect','executor','reviewer','reviewer-architecture','final-reviewer');$AliasRoles=@('executor','reviewer','reviewer-architecture','final-reviewer')
$EligibleFailures=@('PROVIDER_UNAVAILABLE','RATE_LIMIT','PLAN_QUOTA_EXHAUSTED','MODEL_RETIRED','MODEL_TEMPORARILY_UNAVAILABLE','BOUNDED_TIMEOUT');$OnlyOnFailures=$EligibleFailures+@('MODEL_UNAVAILABLE_ON_ALL_CONFIGURED_PROVIDERS');$WorkClasses=@('PATCH','BOUNDED_FEATURE','MAJOR_FEATURE','EXISTING_PRODUCT_EVOLUTION','NEW_PRODUCT','HIGH_RISK_CHANGE')
function Write-Utf8NoBom([string]$Path,[string]$Text){[IO.File]::WriteAllText($Path,$Text,(New-Object Text.UTF8Encoding($false)))}
function Resolve-ModelInput([string]$Value,[string]$Prompt,[string]$ParameterName){if(-not[string]::IsNullOrWhiteSpace($Value)){return$Value};if($NonInteractive){throw"$ParameterName is required in non-interactive mode."};return Read-Host$Prompt}
function Resolve-VariantInput([string]$Value,[string]$Prompt,[bool]$WasBound){if($WasBound){return$Value};if($NonInteractive){return''};return Read-Host$Prompt}
function Get-Role([object]$Routing,[string]$Role){$p=$Routing.roles.PSObject.Properties[$Role];if(-not$p){throw"Routing profile missing role: $Role"};return$p.Value}
function Test-ModelId([string]$Model,[string]$Context){if([string]::IsNullOrWhiteSpace($Model)-or$Model-notmatch'^[^/\s]+/\S+$'){throw"$Context model must use concrete provider/model format."}}
function Get-OnlyOn([object]$Candidate,[string]$Context){if(-not$Candidate.PSObject.Properties['only_on']){throw"$Context only_on must be present; use an empty array for any eligible failure."};return@($Candidate.only_on|Where-Object{-not[string]::IsNullOrWhiteSpace([string]$_)})}
function Get-WorkClasses([object]$Candidate,[string]$Role,[string]$Context){$values=@($Candidate.work_classes|Where-Object{-not[string]::IsNullOrWhiteSpace([string]$_)});if($Role-ne'executor'-and$values.Count){throw"$Context work_classes is valid only for Executor routes."};foreach($value in$values){if([string]$value-notin$WorkClasses){throw"$Context contains invalid work class: $value"}};return$values}
function Validate-Candidate([object]$Candidate,[string]$Role,[string]$Context,[bool]$NeedsPriority){if(-not$Candidate){throw"$Context candidate is required."};Test-ModelId([string]$Candidate.model)$Context;if([string]::IsNullOrWhiteSpace([string]$Candidate.model_family)){throw"$Context model_family is required."};$policy=[string]$Candidate.variant_policy;$variant=[string]$Candidate.variant;if($policy-notin@('explicit','provider_default','highest_supported')){throw"$Context variant_policy is invalid."};if($policy-eq'explicit'-and[string]::IsNullOrWhiteSpace($variant)){throw"$Context explicit variant is required."};if($policy-eq'provider_default'-and-not[string]::IsNullOrWhiteSpace($variant)){throw"$Context provider_default must use a null/blank variant."};if($policy-eq'highest_supported'-and[string]::IsNullOrWhiteSpace($variant)){throw"$Context highest_supported must be resolved locally to a concrete variant before installation."};if($variant-eq'highest_supported'){throw"$Context cannot use highest_supported as a literal variant."};if($NeedsPriority){$priority=0;if(-not[int]::TryParse([string]$Candidate.priority,[ref]$priority)-or$priority-lt1){throw"$Context priority must be a positive integer."}};foreach($failure in(Get-OnlyOn$Candidate$Context)){if([string]$failure-notin$OnlyOnFailures){throw"$Context contains unsupported only_on value: $failure"}};Get-WorkClasses$Candidate$Role$Context|Out-Null}
$Routing=$null;$ManagedAliases=@();$RouteMetadata=@{}
if($RoutingConfigPath){if(-not(Test-Path$RoutingConfigPath-PathType Leaf)){throw"Routing profile not found: $RoutingConfigPath"};try{$Routing=Get-Content$RoutingConfigPath-Raw|ConvertFrom-Json}catch{throw"Invalid routing profile JSON: $RoutingConfigPath"};if([string]$Routing.schema_version-ne'1.0'){throw'Routing schema_version must be 1.0.'};if(-not$Routing.settings-or-not$Routing.roles){throw'Routing profile requires settings and roles.'};$cooldown=0;if(-not[int]::TryParse([string]$Routing.settings.default_cooldown_seconds,[ref]$cooldown)-or$cooldown-lt60-or$cooldown-gt86400){throw'default_cooldown_seconds must be between 60 and 86400.'};foreach($failure in@($Routing.settings.eligible_failures)){if([string]$failure-notin$EligibleFailures){throw"Unsupported eligible failure: $failure"}};foreach($role in@($Routing.settings.enabled_roles)){if([string]$role-notin$SupportedFailoverRoles){throw"Unsupported v3.3 failover role: $role"}};foreach($role in@('architect','executor','reviewer','reviewer-architecture','final-reviewer')){$cfg=Get-Role$Routing$role;Validate-Candidate$cfg.primary$role"$role primary"$false;$priorities=@();foreach($candidate in@($cfg.fallbacks)){Validate-Candidate$candidate$role"$role fallback"$true;$priority=[int]$candidate.priority;if($priorities-contains$priority){throw"$role fallback priorities must be unique."};$priorities+=$priority};if($role-in@($Routing.settings.enabled_roles)-and@($cfg.fallbacks).Count-eq0){throw"$role failover is enabled but no fallback is configured."}}
 $a=(Get-Role$Routing'architect').primary;$e=(Get-Role$Routing'executor').primary;$i=(Get-Role$Routing'reviewer').primary;$s=(Get-Role$Routing'reviewer-architecture').primary;$f=(Get-Role$Routing'final-reviewer').primary;$ArchitectModel=[string]$a.model;$ArchitectVariant=[string]$a.variant;$ExecutorModel=[string]$e.model;$ExecutorVariant=[string]$e.variant;$ReviewerImplementationModel=[string]$i.model;$ReviewerImplementationVariant=[string]$i.variant;$ReviewerArchitectureModel=[string]$s.model;$ReviewerArchitectureVariant=[string]$s.variant;$FinalReviewerModel=[string]$f.model;$FinalReviewerVariant=[string]$f.variant;$RouteMetadata['architect']=$a;$RouteMetadata['build']=$a;$RouteMetadata['plan']=$a;$RouteMetadata['executor']=$e;$RouteMetadata['reviewer']=$i;$RouteMetadata['reviewer-architecture']=$s;$RouteMetadata['final-reviewer']=$f
}else{$ArchitectModel=Resolve-ModelInput$ArchitectModel'Architect model ID (provider/model)''ArchitectModel';$ArchitectVariant=Resolve-VariantInput$ArchitectVariant'Architect variant/reasoning (optional)'($PSBoundParameters.ContainsKey('ArchitectVariant'));$ExecutorModel=Resolve-ModelInput$ExecutorModel'Executor model ID (provider/model)''ExecutorModel';$ExecutorVariant=Resolve-VariantInput$ExecutorVariant'Executor variant/reasoning (optional)'($PSBoundParameters.ContainsKey('ExecutorVariant'));$ReviewerImplementationModel=Resolve-ModelInput$ReviewerImplementationModel'Implementation Reviewer model ID (provider/model)''ReviewerImplementationModel';$ReviewerImplementationVariant=Resolve-VariantInput$ReviewerImplementationVariant'Implementation Reviewer variant/reasoning (optional)'($PSBoundParameters.ContainsKey('ReviewerImplementationVariant'));$ReviewerArchitectureModel=Resolve-ModelInput$ReviewerArchitectureModel'Architecture/Security Reviewer model ID (provider/model)''ReviewerArchitectureModel';$ReviewerArchitectureVariant=Resolve-VariantInput$ReviewerArchitectureVariant'Architecture/Security Reviewer variant/reasoning (optional)'($PSBoundParameters.ContainsKey('ReviewerArchitectureVariant'));$FinalReviewerModel=Resolve-ModelInput$FinalReviewerModel'Final Reviewer/Judge model ID (provider/model)''FinalReviewerModel';$FinalReviewerVariant=Resolve-VariantInput$FinalReviewerVariant'Final Reviewer/Judge variant/reasoning (optional)'($PSBoundParameters.ContainsKey('FinalReviewerVariant'))}
foreach($model in@($ArchitectModel,$ExecutorModel,$ReviewerImplementationModel,$ReviewerArchitectureModel,$FinalReviewerModel)){Test-ModelId$model'Configured role'}
New-Item-ItemType Directory-Force-Path@((Join-Path$ConfigDir'agents'),(Join-Path$ConfigDir'commands'),$BackupDir)|Out-Null
function Backup-IfExists([string]$Path){if(Test-Path$Path-PathType Leaf){Copy-Item$Path(Join-Path$BackupDir(Split-Path$Path-Leaf))-Force}}
foreach($name in$PublicAgents){Backup-IfExists(Join-Path$ConfigDir"agents\$name.md")};foreach($name in$Commands){Backup-IfExists(Join-Path$ConfigDir"commands\$name.md")};Backup-IfExists(Join-Path$ConfigDir'opencode.jsonc');Backup-IfExists(Join-Path$ConfigDir'opencode.json');Backup-IfExists$RoutingManifestPath
if(Test-Path$RoutingManifestPath-PathType Leaf){try{$old=Get-Content$RoutingManifestPath-Raw|ConvertFrom-Json}catch{throw'Existing routing manifest is invalid; refusing to remove managed aliases.'};foreach($alias in@($old.managed_aliases)){$alias=[string]$alias;if($alias-notmatch'^(executor|reviewer|reviewer-architecture|final-reviewer)-fallback-[0-9]+$'){throw"Unsafe managed alias in previous manifest: $alias"};$path=Join-Path$ConfigDir"agents\$alias.md";Backup-IfExists$path;Remove-Item$path-Force-ErrorAction SilentlyContinue};Remove-Item$RoutingManifestPath-Force}
$LegacyAiEditPattern='(?m)^  edit:\r?\n    "\*": deny\r?\n    "\.ai/\*\*": allow\r?\n';$PortableAiEditBlock=@'
  edit:
    "*": deny
    ".ai": allow
    ".ai/*": allow
    "*/.ai": allow
    "*/.ai/*": allow
    '.ai\*': allow
    '*\.ai': allow
    '*\.ai\*': allow
'@
function Add-RouteMetadata([string]$Text,[string]$Role,[string]$RouteAgent,[object]$Candidate,[int]$Priority,[bool]$HiddenAlias){if($HiddenAlias){$Text=[regex]::Replace($Text,'(?m)^mode: subagent\r?$',"mode: subagent`nhidden: true",1)};$variant=if([string]::IsNullOrWhiteSpace([string]$Candidate.variant)){'PROVIDER_DEFAULT'}else{[string]$Candidate.variant};$only=Get-OnlyOn$Candidate"$RouteAgent route";$onlyText=if($only.Count-eq0){'ANY_ELIGIBLE_FAILURE'}else{$only-join'|'};$classes=Get-WorkClasses$Candidate$Role"$RouteAgent route";$classText=if($classes.Count-eq0){'ALL'}else{$classes-join'|'};$rebalance=if($Candidate.requires_role_rebalance-eq$true){'YES'}else{'NO'};$block=@"

## MODEL_ROUTE_METADATA

AUTHORITATIVE_ROLE: $Role
ROUTE_AGENT: $RouteAgent
SELECTED_MODEL: $($Candidate.model)
SELECTED_VARIANT: $variant
MODEL_FAMILY: $($Candidate.model_family)
ROUTE_PRIORITY: $Priority
ROUTE_ONLY_ON: $onlyText
ROUTE_WORK_CLASSES: $classText
REQUIRES_ROLE_REBALANCE: $rebalance

Require matching attempt, packet and frozen-target identifiers plus a complete report. Never read or continue partial output.
"@;return[regex]::Replace($Text,'(?s)\A(---\r?\n.*?\r?\n---\r?\n)',('$1'+$block),1)}
function Render-Agent([string]$Template,[string]$Name,[string]$ModelToken,[string]$Model,[string]$VariantToken,[string]$Variant,[string]$Role,[object]$Candidate,[int]$Priority,[bool]$HiddenAlias){$source=Join-Path$RootDir"templates\agents\$Template.md";$destination=Join-Path$ConfigDir"agents\$Name.md";$text=Get-Content$source-Raw;$text=$text.Replace($ModelToken,$Model);$variantLine=if([string]::IsNullOrWhiteSpace($Variant)){''}else{"variant: $Variant"};$text=$text.Replace($VariantToken,$variantLine);if($Template-ne'executor'){if($text-notmatch$LegacyAiEditPattern){throw"Cannot render portable .ai permissions for $source."};$text=[regex]::Replace($text,$LegacyAiEditPattern,($PortableAiEditBlock.TrimEnd()+"`n"))};if($Candidate){$text=Add-RouteMetadata$text$Role$Name$Candidate$Priority$HiddenAlias};Write-Utf8NoBom$destination$text}
function Render-Public([string]$Name,[string]$Template,[string]$ModelToken,[string]$Model,[string]$VariantToken,[string]$Variant,[string]$Role){$candidate=if($Routing){$RouteMetadata[$Name]}else{$null};Render-Agent$Template$Name$ModelToken$Model$VariantToken$Variant$Role$candidate 0 $false}
Render-Public'architect''architect''__ARCHITECT_MODEL__'$ArchitectModel'__ARCHITECT_VARIANT_LINE__'$ArchitectVariant'architect';Render-Public'build''build''__ARCHITECT_MODEL__'$ArchitectModel'__ARCHITECT_VARIANT_LINE__'$ArchitectVariant'architect';Render-Public'plan''plan''__ARCHITECT_MODEL__'$ArchitectModel'__ARCHITECT_VARIANT_LINE__'$ArchitectVariant'architect';Render-Public'executor''executor''__EXECUTOR_MODEL__'$ExecutorModel'__EXECUTOR_VARIANT_LINE__'$ExecutorVariant'executor';Render-Public'reviewer''reviewer''__REVIEWER_IMPLEMENTATION_MODEL__'$ReviewerImplementationModel'__REVIEWER_IMPLEMENTATION_VARIANT_LINE__'$ReviewerImplementationVariant'reviewer';Render-Public'reviewer-architecture''reviewer-architecture''__REVIEWER_ARCHITECTURE_MODEL__'$ReviewerArchitectureModel'__REVIEWER_ARCHITECTURE_VARIANT_LINE__'$ReviewerArchitectureVariant'reviewer-architecture';Render-Public'final-reviewer''final-reviewer''__FINAL_REVIEWER_MODEL__'$FinalReviewerModel'__FINAL_REVIEWER_VARIANT_LINE__'$FinalReviewerVariant'final-reviewer'
if($Routing){$map=@{'executor'=@('executor','__EXECUTOR_MODEL__','__EXECUTOR_VARIANT_LINE__');'reviewer'=@('reviewer','__REVIEWER_IMPLEMENTATION_MODEL__','__REVIEWER_IMPLEMENTATION_VARIANT_LINE__');'reviewer-architecture'=@('reviewer-architecture','__REVIEWER_ARCHITECTURE_MODEL__','__REVIEWER_ARCHITECTURE_VARIANT_LINE__');'final-reviewer'=@('final-reviewer','__FINAL_REVIEWER_MODEL__','__FINAL_REVIEWER_VARIANT_LINE__')};$policy=@();foreach($role in$AliasRoles){if($role-notin@($Routing.settings.enabled_roles)){continue};$cfg=Get-Role$Routing$role;foreach($candidate in@($cfg.fallbacks|Sort-Object{[int]$_.priority})){$alias="$role-fallback-$([int]$candidate.priority)";$ManagedAliases+=$alias;$m=$map[$role];Render-Agent$m[0]$alias$m[1]([string]$candidate.model)$m[2]([string]$candidate.variant)$role$candidate([int]$candidate.priority)$true;$only=Get-OnlyOn$candidate"$alias route";$classes=Get-WorkClasses$candidate$role"$alias route";$policy+="- $role -> $alias; priority=$($candidate.priority); family=$($candidate.model_family); only_on=$(if($only.Count){$only-join'|'}else{'ANY'}); work_classes=$(if($classes.Count){$classes-join'|'}else{'ALL'})"}}
 $architectEnabled='architect'-in@($Routing.settings.enabled_roles);$executorEnabled='executor'-in@($Routing.settings.enabled_roles);$top=if($architectEnabled){'Architect top-level failover uses `scripts/run-governed.ps1|sh` only for `ai-init|ai-audit|ai-discover|ai-plan`.'}else{'Architect top-level failover is disabled.'};$executorPolicy=if($executorEnabled){'Executor failover must use `scripts/executor-attempt.ps1|sh`: select an eligible work-class route, prepare a detached worktree under `.ai/executor-worktrees`, run the complete `EXECUTION_PACKET` inside `EXECUTION_ROOT`, discard on eligible model failure, finalize only a matching `REPORT_COMPLETE: YES`, then promote the verified binary patch. Never delegate an Executor route against the real project root.'}else{'Executor failover is disabled.'};$block=@"

## ROLE_FAILOVER_POLICY

Eligible failures: $(@($Routing.settings.eligible_failures)-join'|'). Ineligible or unclassified failures stop. Every fallback restarts the complete role/command; active fallback attempts are sticky; primary returns only on a later task after cooldown. Provider/rate/quota failure prefers the same family, while retired/globally unavailable families are skipped. Never retry the same route.

$top

$executorPolicy

Reviewer/final routes retain frozen packet/target evidence and actual-family independence. Executor promotion is not validation and normal review/commit gates remain mandatory.

Configured hidden routes:
$($policy-join"`n")
"@;foreach($name in@('architect','build')){$path=Join-Path$ConfigDir"agents\$name.md";$text=Get-Content$path-Raw;$rules="    `"executor-fallback-*`": allow`n    `"reviewer-fallback-*`": allow`n    `"reviewer-architecture-fallback-*`": allow`n    `"final-reviewer-fallback-*`": allow";$text=[regex]::Replace($text,'(?m)^(    final-reviewer: allow\r?$)',("`$1`n"+$rules),1);if($text-match'(?m)^## Core invariants\r?$'){$text=[regex]::Replace($text,'(?m)^## Core invariants\r?$',$block+"`n## Core invariants",1)}else{$text+=$block};Write-Utf8NoBom$path$text};$manifest=[ordered]@{schema_version='1.0';governance_version='3.3.0';settings=$Routing.settings;roles=$Routing.roles;managed_aliases=$ManagedAliases;generated_at=(Get-Date).ToUniversalTime().ToString('o')};Write-Utf8NoBom$RoutingManifestPath(($manifest|ConvertTo-Json-Depth30)+[Environment]::NewLine)}
foreach($name in$Commands){Copy-Item(Join-Path$RootDir"templates\commands\$name.md")(Join-Path$ConfigDir"commands\$name.md")-Force}
$jsonc=Join-Path$ConfigDir'opencode.jsonc';$json=Join-Path$ConfigDir'opencode.json';$target=if((Test-Path$jsonc)-or-not(Test-Path$json)){$jsonc}else{$json};if(Test-Path$target){$raw=Get-Content$target-Raw;$stripped=[regex]::Replace($raw,'/\*.*?\*/','','Singleline');$stripped=[regex]::Replace($stripped,'(?m)^\s*//.*$','');$stripped=[regex]::Replace($stripped,',\s*([}\]])','$1');if([string]::IsNullOrWhiteSpace($stripped)){$object=[pscustomobject][ordered]@{'$schema'='https://opencode.ai/config.json'}}else{try{$object=$stripped|ConvertFrom-Json}catch{throw"Cannot safely merge $target. Restore the backup and set default_agent manually."}}}else{$object=[pscustomobject][ordered]@{'$schema'='https://opencode.ai/config.json'}};$object|Add-Member-MemberType NoteProperty-Name'default_agent'-Value'architect'-Force;Write-Utf8NoBom$target(($object|ConvertTo-Json-Depth20)+[Environment]::NewLine)
&(Join-Path$PSScriptRoot'verify.ps1')-ConfigDir$ConfigDir;&(Join-Path$PSScriptRoot'verify-routing.ps1')-ConfigDir$ConfigDir
$mode=if($Routing){"routing manifest with $($ManagedAliases.Count) hidden routes"}else{'legacy single-model routing'};Write-Host"Installed OpenCode Governance v3.3.0: 7 public agents, 12 commands, $mode.";Write-Host'Executor fallback is isolated and requires executor-attempt.ps1/sh. Promotion never bypasses normal review or commit gates.';Write-Host'No push, merge, deployment or production rollback is automatic. Restart OpenCode before use.';Write-Host"Backup: $BackupDir"
