#!/usr/bin/env python3
"""AUTHORITATIVE_ROUTE_RECEIPT_V1 — strict route-receipt schema (S-014).

4.0.2 accepted any JSON containing route_id and model_family as a route receipt.
4.0.3 introduces a strict, hash-bound receipt generated by the route runner and
revalidated by ingestion and the Review Chain V4. No caller-provided string may
substitute for a runner receipt.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import re
import sys
import time
from typing import Any

SCHEMA = "AUTHORITATIVE_ROUTE_RECEIPT_V1"
SHA256_RE = re.compile(r"^[a-f0-9]{64}$")
REQUIRED_FIELDS = (
    "schema", "route_id", "role", "task_id", "packet_sha256",
    "candidate_identity", "model", "variant", "model_family",
    "provider_route_identity", "selection_policy_sha256", "launch_sha256",
    "role_process_receipt_sha256", "process_id", "session_id",
    "started_at_utc", "completed_at_utc",
)


def emit_error(code: str, detail: str = "") -> None:
    payload = {"status": "ERROR", "code": code, "contract": SCHEMA}
    if detail:
        payload["detail"] = detail
    print(json.dumps(payload, sort_keys=True), file=sys.stderr)
    raise SystemExit(2)


def sha256_file(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def validate_receipt(body: dict[str, Any], *, expected_role: str | None = None,
                     expected_packet: str | None = None) -> dict[str, Any]:
    """S-014: strict validation. Returns the validated body or raises."""
    if not isinstance(body, dict):
        emit_error("ROUTE_RECEIPT_INVALID", "not a json object")
    if body.get("schema") != SCHEMA:
        emit_error("ROUTE_RECEIPT_SCHEMA_INVALID", str(body.get("schema")))
    for f in REQUIRED_FIELDS:
        v = str(body.get(f) or "").strip()
        if not v:
            emit_error("ROUTE_RECEIPT_FIELD_MISSING", f)
    for f in ("packet_sha256", "selection_policy_sha256", "launch_sha256", "role_process_receipt_sha256"):
        if not SHA256_RE.fullmatch(str(body.get(f) or "")):
            emit_error("ROUTE_RECEIPT_SHA256_INVALID", f)
    if expected_role and str(body.get("role")) != expected_role:
        emit_error("ROUTE_RECEIPT_ROLE_MISMATCH", f"expected={expected_role} got={body.get('role')}")
    if expected_packet and str(body.get("packet_sha256")) != expected_packet:
        emit_error("ROUTE_RECEIPT_PACKET_MISMATCH", f"expected={expected_packet} got={body.get('packet_sha256')}")
    # Chronology sanity.
    if str(body.get("started_at_utc")) > str(body.get("completed_at_utc")):
        emit_error("ROUTE_RECEIPT_CHRONOLOGY_INVALID")
    return body


def write_receipt(out: pathlib.Path, body: dict[str, Any]) -> dict[str, Any]:
    out = pathlib.Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.parent.exists() and out.parent.is_symlink():
        emit_error("ROUTE_RECEIPT_PATH_SYMLINK", str(out.parent))
    data = (json.dumps(body, indent=2, sort_keys=True) + "\n").encode("utf-8")
    tmp = out.with_suffix(out.suffix + ".tmp")
    tmp.write_bytes(data)
    os.replace(tmp, out)
    try:
        os.chmod(out, 0o600)
    except OSError:
        pass
    digest = hashlib.sha256(data).hexdigest()
    return {"status": "ROUTE_RECEIPT_WRITTEN", "contract": SCHEMA, "path": str(out), "sha256": digest}


def emit(*, role: str, task_id: str, route_id: str, model: str, variant: str,
         model_family: str, provider_route_identity: str, packet_sha256: str,
         candidate_identity: str, selection_policy_sha256: str, launch_sha256: str,
         role_process_receipt_sha256: str, process_id: int, session_id: str,
         started_at_utc: str, completed_at_utc: str | None = None,
         out: pathlib.Path) -> dict[str, Any]:
    body = {
        "schema": SCHEMA,
        "route_id": route_id,
        "role": role,
        "task_id": task_id,
        "packet_sha256": packet_sha256,
        "candidate_identity": candidate_identity,
        "model": model,
        "variant": variant,
        "model_family": model_family,
        "provider_route_identity": provider_route_identity,
        "selection_policy_sha256": selection_policy_sha256,
        "launch_sha256": launch_sha256,
        "role_process_receipt_sha256": role_process_receipt_sha256,
        "process_id": int(process_id),
        "session_id": session_id,
        "started_at_utc": started_at_utc,
        "completed_at_utc": completed_at_utc or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    validate_receipt(body, expected_role=role, expected_packet=packet_sha256)
    return write_receipt(out, body)


def main() -> int:
    p = argparse.ArgumentParser(prog="route-receipt")
    sub = p.add_subparsers(dest="cmd", required=True)
    e = sub.add_parser("emit")
    e.add_argument("--out", required=True)
    e.add_argument("--role", required=True)
    e.add_argument("--task-id", required=True)
    e.add_argument("--route-id", required=True)
    e.add_argument("--model", required=True)
    e.add_argument("--variant", default="")
    e.add_argument("--model-family", required=True)
    e.add_argument("--provider-route-identity", required=True)
    e.add_argument("--packet-sha256", required=True)
    e.add_argument("--candidate-identity", required=True)
    e.add_argument("--selection-policy-sha256", required=True)
    e.add_argument("--launch-sha256", required=True)
    e.add_argument("--role-process-receipt-sha256", required=True)
    e.add_argument("--process-id", type=int, required=True)
    e.add_argument("--session-id", default="")
    e.add_argument("--started-at-utc", required=True)
    e.add_argument("--completed-at-utc", default="")
    v = sub.add_parser("validate")
    v.add_argument("--receipt", required=True)
    v.add_argument("--expected-role", default="")
    v.add_argument("--expected-packet", default="")
    args = p.parse_args()
    if args.cmd == "emit":
        result = emit(
            out=pathlib.Path(args.out), role=args.role, task_id=args.task_id, route_id=args.route_id,
            model=args.model, variant=args.variant, model_family=args.model_family,
            provider_route_identity=args.provider_route_identity, packet_sha256=args.packet_sha256,
            candidate_identity=args.candidate_identity, selection_policy_sha256=args.selection_policy_sha256,
            launch_sha256=args.launch_sha256, role_process_receipt_sha256=args.role_process_receipt_sha256,
            process_id=args.process_id, session_id=args.session_id, started_at_utc=args.started_at_utc,
            completed_at_utc=args.completed_at_utc,
        )
        print(json.dumps(result, sort_keys=True))
        return 0
    receipt_path = pathlib.Path(args.receipt)
    if not receipt_path.is_file() or receipt_path.is_symlink():
        emit_error("ROUTE_RECEIPT_MISSING", str(receipt_path))
    body = json.loads(receipt_path.read_text(encoding="utf-8"))
    validate_receipt(body, expected_role=args.expected_role or None, expected_packet=args.expected_packet or None)
    print(json.dumps({"status": "ROUTE_RECEIPT_VALID", "sha256": sha256_file(receipt_path)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
